[package]
name = "smartcore"
version = "0.1.0"
authors = ["Vlad Orlov"]
edition = "2018"

[dependencies]
ndarray = "0.13"
num-traits = "0.2.11"
num = "0.2.1"
rand = "0.7.3"
serde = { version = "1.0.105", features = ["derive"] }
serde_derive = "1.0.105"

[dev-dependencies]
criterion = "0.3"
serde_json = "1.0"
bincode = "1.2.1"

[[bench]]
name = "distance"
harness = false