[package]
name = "smartcore"
version = "0.1.0"
authors = ["Vlad Orlov"]
edition = "2018"

[dependencies]
ndarray = "0.13"
num-traits = "0.2.11"
num = "0.2.1"
rand = "0.7.3"

[dev-dependencies]
ndarray = "0.13"
criterion = "0.3"

[[bench]]
name = "distance"
harness = false